### ISSUE TITLE
MDS analysis plot

### ISSUE THREAD

**Issue by ryamy** [the-protein-engineering-tournament/pet-pilot-2023#10]
Thanks for your great work! I found the MDS analysis plot on Fig. 4, could you show us the code of MDS analysis? I think this plot is very useful , and I would like to create same plot on my own data. I am just interested in how to create distance matrix represent sequence distance and number of mutations simultaneously.

**Comment by hredestig** [comment]
Thanks for patience with slow reply. Here's the code for the MDS plot https://github.com/debbiemarkslab/sequenceMDS/blob/main/sequenceMDS%20example%202%20-%20alignbio%20tournament%202023.ipynb
