### ISSUE TITLE
Team Methodologies?

### ISSUE THREAD

**Issue by eyesmo** [the-protein-engineering-tournament/pet-pilot-2023#9]
I can see this repo contains the code for analyzing and scoring the submissions from each PET2023 team; but are the methods/pipelines each team used to generate their submissions documented anywhere? Is there a manuscript in preparation that reports each methodology used by each team on each task?

**Comment by hredestig** [comment]
[This](https://github.com/the-protein-engineering-tournament/pet-pilot-2023/blob/main/doc/Compiled%20Abstracts%20from%20Participating%20Teams%202023.pdf) is the only currently available documentation available on the methods.  There is a manuscript for the PET pilot in preparation but it is up to participants to decide how to disseminate their approaches.
